kind: PersistentVolume
apiVersion: v1
metadata:
  name: sandbox-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: volumeid
    fsType: ext4