- name: install required packages
  yum:
    name: 
      - openswan
    state: present

- name: Copy ipsec conf
  copy:
    src: ipsec.conf
    dest: "/etc/ipsec.conf"
    owner: root
    group: root
    mode: '0644'

- name: Copy tunnel config
  template:
    src: tunnel.conf.j2
    dest: "/etc/ipsec.d/tunnel.conf"
    owner: root
    group: root
    mode: '0644'

- name: Generate shared key
  set_fact:
    ipsec_shared_key: SMUwRvCYYWmptXI
  delegate_to: localhost

- name: Copy tunnel config
  template:
    src: tunnel.secrets.j2
    dest: "/etc/ipsec.d/tunnel.secrets"
    owner: root
    group: root
    mode: '0600'

- name: Enable service ipsec
  service:
    name: ipsec
    enabled: yes

- name: Restart ipsec service
  service:
    name: ipsec
    state: restarted

- name: Restart network service
  service:
    name: network
    state: restarted

- name: net.ipv4.ip_forward=1
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.all.accept_redirects = 0
  sysctl: name="net.ipv4.conf.all.accept_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.all.send_redirects = 0
  sysctl: name="net.ipv4.conf.all.send_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.default.send_redirects = 0
  sysctl: name="net.ipv4.conf.default.send_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.eth0.send_redirects = 0
  sysctl: name="net.ipv4.conf.eth0.send_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.default.accept_redirects = 0
  sysctl: name="net.ipv4.conf.default.accept_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.eth0.accept_redirects = 0
  sysctl: name="net.ipv4.conf.eth0.accept_redirects" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.all.rp_filter = 0
  sysctl: name="net.ipv4.conf.all.rp_filter" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.default.rp_filter = 0
  sysctl: name="net.ipv4.conf.default.rp_filter" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.eth0.rp_filter = 0
  sysctl: name="net.ipv4.conf.eth0.rp_filter" value=0 sysctl_set=yes state=present reload=yes

- name: net.ipv4.conf.ip_vti0.rp_filter = 0
  sysctl: name="net.ipv4.conf.ip_vti0.rp_filter" value=0 sysctl_set=yes state=present reload=yes



